### ISSUE TITLE
Keep the tag word when use Backspace key

### ISSUE THREAD

**Issue by CrafterSama** [hc-oss/react-tag-input-component#10]
Adding the comma and space key to the add trigger to separate the tags and when use the Backspace the word keep for corrections or something like that

**Comment by CrafterSama** [comment]
@harshzalavadiya Oh ok, thx for adding that feature, could I make the improvement for the Backspace?

**Comment by CrafterSama** [comment]
Possible Solution here #11

**Comment by harshzalavadiya** [comment]
@CrafterSama 
I'm sorry but can you elobrate a little about #11 what problem it solves?

**Comment by CrafterSama** [comment]
@harshzalavadiya I Change the Issue title, I'm sorry about it, but the issue indeed it's that the word it's totally removed when you press Backspace key, the PR solve this keeping the word when you remove the tag with Backspace Key.

If you review the PR, it's really clear in the code to keep the word when it's removed with the Backspace.

**Comment by harshzalavadiya** [comment]
@CrafterSama instead of changing this behaviour directly, can this be behind flag/prop?
since default behaviour is wildly accepted by other libraries https://react-select.com/creatable

**Comment by CrafterSama** [comment]
@harshzalavadiya Yes I can make that change, to make it optional, I think about after to make the PR, but I want to know what do tou think about it first...

**Comment by harshzalavadiya** [comment]
Closing since PR is already merged
