### ISSUE TITLE
How add tags - beforeAddValidate

### ISSUE THREAD

**Issue by brenolapreza** [hc-oss/react-tag-input-component#17]
I want to validate the input type, allowing only numbers. Can I do this with the "beforeAddValidate" function?

If yes, how do I add the tags after using this function?

**Comment by harshzalavadiya** [comment]
@brenolapreza here's sample for `beforeAddValidate` method

https://github.com/hc-oss/react-tag-input-component/blob/master/stories/tags-input.stories.tsx#L14-L20
