### ISSUE TITLE
I can't get data to state, i can only type it to component ( which change the state )

### ISSUE THREAD

**Issue by BilliNovik** [hc-oss/react-tag-input-component#18]
Hello, my codesandbox is available => https://codesandbox.io/s/frosty-http-vk7xy8?file=/src/App.js. The problem is **I can't get data**. How can I change it without typing ?
``const getData = async () => {``
   ``const { data } = await getParams();``
    ``setSelected(data[0].phrase); `` **--array**
  ``};``

**Comment by harshzalavadiya** [comment]
@BilliNovik as of now this component only has uncontrolled way of managing state
you can either force reload component using `key` prop and change it but I'm keeping it open so in future I can provide this feature

for now you can make it work this way, but not the most elegant solution 😅

https://codesandbox.io/s/keen-sea-cgys9j

**Comment by BilliNovik** [comment]
Thank You!!!
