### ISSUE TITLE
It is triggering the onChange on the first render

### ISSUE THREAD

**Issue by p4scu41** [hc-oss/react-tag-input-component#20]
An excellent and easy-to-use component, but unfortunately it is triggering automatically the onChange event when it renders for the first time, Is it expected behavior?

**Comment by harshzalavadiya** [comment]
@p4scu41 yes, it is expected behaviour since we are just using useEffect internally so it will trigger `onChange` on first run

but I think not triggering `onChange` might be better behaviour
