### ISSUE TITLE
Can I trigger the list below to setState tag input?

### ISSUE THREAD

**Issue by champseo2017** [hc-oss/react-tag-input-component#21]
<img width="376" alt="Screen Shot 2565-09-12 at 11 35 26" src="https://user-images.githubusercontent.com/32265715/189574882-d444c01a-f7d9-48a4-97ea-a3b0fb28a690.png">

I tried to setState at list but it didn't work.

<TagsInput
        value={initMasterTag}
        onChange={funcHandlerOnChange}
        name="createtag"
        placeHolder="Select tag"
        beforeAddValidate={funcBeforeAddValidate}
        onRemoved={funcHandlerOnRemoved}
      />

setInitMasterTag((preventState) => {
        return [...preventState, label]
      })

**Comment by harshzalavadiya** [comment]
@champseo2017 you might be looking for this?

https://github.com/hc-oss/react-tag-input-component/issues/18

**Comment by champseo2017** [comment]
oh thank you so much i tried for hours with DOM injection

**Comment by harshzalavadiya** [comment]
enhancement for this is in the pipeline so, in future you might be able to do it without any change
