### ISSUE TITLE
Disable backspace deletion of tags

### ISSUE THREAD

**Issue by bartvdklu** [hc-oss/react-tag-input-component#25]
Hi,

Is it possible to change or remove te key you use to delete tags from the input field.
Now If you use backspace in an empty input field it removes te last tag. Is it possible to turn this on or of?

I want to use it for my project but the backspace doesn't use OnRemove. It's projecting some problems for my project.

**Comment by harshzalavadiya** [comment]
@bartvdklu sadly we don't have any way to customise it but I will be adding in future
