### ISSUE TITLE
Space separators is not working

### ISSUE THREAD

**Issue by ranjit-redekar** [hc-oss/react-tag-input-component#33]
I have added separators like below and it's not working.
separators={['Space', 'Enter']}

after space tag is not getting add.

**Comment by harshzalavadiya** [comment]
@ranjit-redekar `Space` does not require any special keyword like `Enter` just use it like below

```
separators={[" ", "Enter"]}
```

**Comment by danny-dang** [comment]
@harshzalavadiya Please update this in the docs, it's confusing
